### PR TITLE
update deployment lifecycle

### PR DESCRIPTION
**Pull request by vabarbosa**
## Changes

- make deployment `inactive` on clean action
- reuse existing deployments on multiple updates to same PR

## Implementation details

- use `cloudposse/github-action-seek-deployment` to find current deployment
- use `bobheadxi/deployments` to update deployment status

## How to read this PR

- review usage of [cloudposse/github-action-seek-deployment@main](https://github.com/marketplace/actions/seek-deployment)
- review usage of [bobheadxi/deployments@v1](https://github.com/marketplace/actions/github-deployments)
- review deploy steps
- review clean steps
- use this [test PR](https://github.com/Qiskit/saiba/pull/258) to open/close/commit and see the [deployment changes](https://github.com/Qiskit/saiba/deployments).

### CODE REVIEW

**Comment by abdonrd** [comment]
I just test it, but something looks wrong.

Because #268 here I see:
Screenshot 2022-11-04 at 10 05 43 AM

There is no deployment.
Also not appear here https://github.com/Qiskit/saiba/deployments:

Screenshot 2022-11-04 at 10 06 26 AM

**Comment by vabarbosa** [comment]
it is actually here: https://github.com/Qiskit/saiba/deployments/activity_log?page=3
image

this PR as part of updating the deployment lifecycle,  re-uses the deployment if a previous one was found based on the ref (i.e., branch):

https://github.com/Qiskit/gh-actions/blob/cb1a9a2a2f1fadd2aa9d4fa091a568d1f4a86f25/.github/workflows/code-engine-cleanup.yml#L69-L88

it can be changed if that is not a desired behavior... i dont mind either way (reuse or create new)

**Comment by abdonrd** [comment]
Oh!

Here I expect to see the deployment:

https://user-images.githubusercontent.com/1007051/199993089-033e7308-0d38-401d-833a-930911d9a8a4.png

**Comment by vabarbosa** [comment]
oh 🤔 
if iemember correctly that is because of the current action which deactivates existing deployments whenever a new one is activated... which is why we are trying to update the action so it does not  do that

**Comment by abdonrd** [comment]
And thinking the best flow, I guess it would be...

- Create a deployment with each commit.

- As now we only want one deployment per branch, if there is already a previous deployment, inactivate it. If in the future we could have a deployment by commit, we would only have to remove this logic.

- When the PR is closed/merged, all deployments are inactivated.

**Comment by abdonrd** [comment]
> oh 🤔 if remember correctly that is because of the current action which deactivates existing deployments whenever a new one is activated... which is why we are trying to update the action so it does not do that

But the last updated PR is https://github.com/Qiskit/saiba/pull/268
No one should have disabled it, right?

**Comment by Eric-Arellano** [comment]
Is this stale? Should we close it?

**Comment by Eric-Arellano** [comment]
This repo isn't getting new development.

**Pull request closed without merging**
